### ISSUE TITLE
Downloads to wrong folder

### ISSUE THREAD

**Issue by bcurran3** [kendaleiv/chocolatey-keepass-keepasshttp#7]
Current package downloads KeePassHttp.plgx to C:\Program Files (x86)\KeePass Password Safe 2 and it needs to go to the Plugins subfolder for KeePass to find and use it. Current result is same as not installed.

**Comment by kendaleiv** [comment]
Want to open a PR if you've got the changes done locally and tested per your comment at https://chocolatey.org/packages/keepass-keepasshttp#comment-3382730893?

**Comment by bcurran3** [comment]
I think I did, but might not have done it right. :)

**Comment by kendaleiv** [comment]
There aren't any open pull requests at https://github.com/kendaleiv/chocolatey-keepass-keepasshttp/pulls.

Judging by your fork I think you'd want to open two pull requests:
https://github.com/kendaleiv/chocolatey-keepass-keepasshttp/compare/master...bcurran3:patch-1
https://github.com/kendaleiv/chocolatey-keepass-keepasshttp/compare/master...bcurran3:patch-2

**Comment by kendaleiv** [comment]
Also, you can test the changes by running `choco pack` locally and installing the package with `choco install keepass-keepasshttp -s .` from the package folder, as well as `choco uninstall keepass-keepasshttp` to test the uninstall.

See https://github.com/chocolatey/choco/wiki/CreatePackages#testing-your-package for more information.

**Comment by bcurran3** [comment]
I tested right after posting. :) Works perfect. Works with -force as well. I didn't try an older version to see if the newer version overwrites the file or though or with KeePass running. 
Hopefull I forked it right.
👍  Thanks. 
(My rice cooker plays music too!)

**Comment by kendaleiv** [comment]
Updated in #8 and #9.

**Comment by bcurran3** [comment]
I updated the nuspec for you too. Not sure if I did it right so that it goes to you. If not, it's here:
https://github.com/bcurran3/chocolatey-keepass-keepasshttp/blob/master/keepass-keepasshttp.nuspec

**Comment by kendaleiv** [comment]
Ah, that works. It would be nice to have it be more clear that it installs `1.8.4.2`, but this might be the best we can do given the constraints of the version number and the guidance at https://github.com/chocolatey/choco/wiki/CreatePackages#versioning-recommendations.

I created a PR at #10 and merged it. Thanks!

**Comment by bcurran3** [comment]
YW!
Yeah, one more decimal support in the version would be nice...

But when you repack and repush it, it will reinstall for everyone and the file will be in the right place.

Now https://chocolatey.org/packages/chromelpass-chrome/2.8.1 will work. :)

**Comment by kendaleiv** [comment]
Published as https://chocolatey.org/packages/keepass-keepasshttp/1.8.4.220170623. Thanks for the contribution!

**Comment by bcurran3** [comment]
Ken - sorry to bug. Looks like the icon isn't showing on the chocolatey package page. You might want to update with     <iconUrl>http://keepass.info/help/images/plockb_64.png</iconUrl> and repush just for esthetics.

**Comment by kendaleiv** [comment]
Hmm, it's showing up for me (https://raw.githubusercontent.com/pfn/keepasshttp/master/logo.png). That's the logo for the [pfn/keepasshttp](https://github.com/pfn/keepasshttp) repository.

**Comment by bcurran3** [comment]
It wasn't showing on the Chocolatey package page....CDN problem, showing fine now!
